### ISSUE TITLE
Promise.race

### ISSUE THREAD

**Issue by kingstone3** [taylorhakes/promise-polyfill#100]
Promise.race(native):
![image](https://user-images.githubusercontent.com/18232598/58951563-02185680-87c4-11e9-91e3-43642babfe11.png)

Promise.race(promise-polyfill):
<img width="653" alt="屏幕快照 2019-06-05 18 53 22" src="https://user-images.githubusercontent.com/18232598/58951458-caa9aa00-87c3-11e9-94d1-29dda4fd4262.png">

https://github.com/taylorhakes/promise-polyfill/blob/master/src/index.js#L219

**Comment by taylorhakes** [comment]
Thanks for identifying that issue. I will work on a fix in the next couple days.
