### ISSUE TITLE
Promise.all([]) not allowed

### ISSUE THREAD

**Issue by TheModMaker** [taylorhakes/promise-polyfill#103]
Promise.all/Promise.race can accept an empty array, but after 74d3029de2c3bada8d27de37d31c6718de69f253 they are not accepted in this polyfill.

**Comment by taylorhakes** [comment]
Thanks for the bug report. I will fix it right away tonight. Sorry about that. I will make sure it’s added to the test suite. Can you point to 8.1.0 temporarily?

**Comment by taylorhakes** [comment]
Fixed in `8.1.2`. Thanks again for the bug report https://github.com/taylorhakes/promise-polyfill/releases/tag/8.1.2
