### ISSUE TITLE
dist/polyfill.min.js missing v8.1.2 fix

### ISSUE THREAD

**Issue by laukstein** [taylorhakes/promise-polyfill#104]
@taylorhakes, your commit https://github.com/taylorhakes/promise-polyfill/commit/03f6f9a0d19e721b4167fdafbe96f0418718a12a that later has been released as v8.1.2 in missing in dist/polyfill.min.js, it should be updated accordingly too.

**Comment by taylorhakes** [comment]
Fixed. Thanks for the bug report
