### ISSUE TITLE
catch causing `expected identifier` in IE8, it seems promise is not returned for chaining

### ISSUE THREAD

**Issue by higherstar** [taylorhakes/promise-polyfill#105]
after declare the polyfill 

I defined a function like below.

var get = function(url) {
  return new Promise(function(resolve, reject) {
    try {
      var xhr = window.XMLHttpRequest ? new XMLHttpRequest() : new ActiveXObject('Microsoft.XMLHTTP');

      xhr.open('GET', url);
      xhr.onreadystatechange = function() {
        try {
          if (xhr.readyState > 3) {   // XMLHttpRequest.DONE == 4
            if (xhr.status === 200) {
              xhr.onreadystatechange = null;
              resolve(xhr.responseText);
            } else {
              reject();
            }
          } catch(e) {
            if (debugMode) {
          }
        }
      };

      xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
      xhr.send();
    } catch(e) {
      if (debugMode) {
        console.log(e);
      }
    }
  });
}

The following code works well in almost all browsers but in IE8, I am getting error
"expected identifier" in the line of `catch` in karma-jasmine test

get('https://ipapi.co/json')
   .then(function(responseText) {
    blablabla()
  })
  .catch(function(e) {
    blabla();
  });

**Comment by taylorhakes** [comment]
`catch` is a reserved word in IE8, so you can't use `.catch`. You need to change your code to this, or use babel to transform your code to support IE8

```js
get('https://ipapi.co/json')
.then(function(responseText) {
  blablabla()
})['catch'](function(e) {
  blabla();
});
```
