### ISSUE TITLE
Unhandled Promise Rejection - Desktop Safari 13.0.2

### ISSUE THREAD

**Issue by tedfitzpatrick** [taylorhakes/promise-polyfill#108]
I'm using promise-polypill for IE 11 support for Webpack 4's dynamic module import feature. Specifically, import "promise-polyfill/src/polyfill"; as the 1st line of my entry index.js. It's working great in IE 11, Chrome, Firefox, Mobile Safari; but in Desktop Safari 13.0.2 my console is reporting Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e[t].call')

**Comment by tedfitzpatrick** [comment]
I should mention that the import Promise from "promise-polyfill"; isn't working in IE 11

**Comment by tedfitzpatrick** [comment]
I found the culprit, Edge doesn't like like it either. In Promise._immediateFn, in the short-circuit assignment,  typeof setImmediate === "function" is used but Safari and Edge can't find setImmediate

**Comment by taylorhakes** [comment]
Thanks for the bug report @tedfitzpatrick. Would you be able to submit a PR with the fix? I would be interested to learn how setImmediate is causing this issue.

**Comment by taylorhakes** [comment]
Closing because of no response.
