### ISSUE TITLE
Missing Promise.allSettled

### ISSUE THREAD

**Issue by cdrini** [taylorhakes/promise-polyfill#116]
`Promise.allSettled` has been accepted and is already in production Firefox/Chrome.

This page has details on implementation / other polyfills that have already implemented it: https://github.com/tc39/proposal-promise-allSettled

Here's the mdn page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

**Comment by hsh2001** [comment]
You can use https://www.npmjs.com/package/promise-all-settled-polyfill

**Comment by taylorhakes** [comment]
There was a previous PR that was abandoned. If someone has time, please add tests and submit a new PR. I will happily merge a PR to add this API. https://github.com/taylorhakes/promise-polyfill/pull/112

**Comment by Jamie5** [comment]
Added #121 which includes tests. Not sure how rigorous we want the tests to be but can adjust as needed.

**Comment by taylorhakes** [comment]
Released in 8.2.0. Thanks @Jamie5
