### ISSUE TITLE
Document meanings of _state values

### ISSUE THREAD

**Issue by gvwilson** [taylorhakes/promise-polyfill#120]
Apologies if I've missed it, but there doesn't appear to be documentation for the various values of `_state` - I think that and a state transition diagram would help newcomers like me understand the code much more reasily. Thanks - Greg

**Comment by taylorhakes** [comment]
Hi @gvwilson. Thanks for the issue report. Unfortunately I don't have time currently create a state transition diagram. If you or someone else has time to create one, I would happily add it to the repo.

**Comment by YellowAfterlife** [comment]
As far as I can tell,`_state` values are:

* 0: pending
* 1: resolved
* 2: rejected
* 3: resolved to a promise

state 3 is distinct because this allows to follow the chain of promises when finalizing.

**Comment by taylorhakes** [comment]
The above is correct. If anyone wants to add documentation to the codebase I welcome a PR. I am going to close this for now
