### ISSUE TITLE
v8.2.1: setImmediate in IE11 can lose its context and throw "Invalid calling object"

### ISSUE THREAD

**Issue by tysonstewart** [taylorhakes/promise-polyfill#132]
After upgrading from v8.2.0 to v8.2.1, I started seeing an error in IE11 when trying to invoke `setImmediate`: "Invalid calling object". Some searching turned up [this issue](https://github.com/reflux/refluxjs/issues/374) which suggested binding the function to the window object. This does in fact work. So one potential solution is to change [this line](https://github.com/taylorhakes/promise-polyfill/blob/a78ac023d17c74be70ab18cef8d2c469e07c07f5/src/index.js#L8) to:

```javascript
var setImmediateFunc = typeof setImmediate !== 'undefined' ? window.setImmediate.bind(window) : null;
```

I'm not sure about side effects such as using polyfills for `setImmediate`, though.

**Comment by taylorhakes** [comment]
This is fixed in 8.2.3.
