### ISSUE TITLE
ES6 Promise compatible

### ISSUE THREAD

**Issue by edwinm** [taylorhakes/promise-polyfill#14]
The documentation status the lib is A+ Compliant, but is says nowhere it's compatible with ES6 Promise. Is it intended to be compatible? Is it 100% compatible? Is that tested? Please improve your documentation.

**Comment by taylorhakes** [comment]
I have updated the documentation with ES6 info. https://github.com/taylorhakes/promise-polyfill/commit/d24eccd6f7a02c517ba7582718b602db4ba53a32
