### ISSUE TITLE
Set minimum permissions for workflows

### ISSUE THREAD

**Issue by gabibguti** [taylorhakes/promise-polyfill#154]
Set minimum permissions to workflows helps keep the workflows more safe against supply-chain attacks. GitHub gives [higher permissions to workflows by default](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) but it's good practice to adjust them to the minimum permissions necessary.

To do that, we check what actions are used in the workflow and what permissions they need. In this case `tests.yml` uses `actions/checkout` and `actions/setup-node`, which need only `contents: read` permissions to read the repository code. If you agree with this setting, I can open a PR!

This setting is recommended by security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

##### Additional Context
I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by taylorhakes** [comment]
Thanks for finding. Happy to accept a PR with this change.
