### ISSUE TITLE
Unable to register a global handler for all unhandled rejected promises

### ISSUE THREAD

**Issue by mitar** [taylorhakes/promise-polyfill#19]
One good thing for debugging is that all unhandled rejections are printer to the console in current browsers. But for this polyfill it seems this is not happening/there is no way to register a global handler which should be called if nothing handles a rejection?

**Comment by taylorhakes** [comment]
@mitar Thanks for the suggestion. I just released 4.0.1 with this ability. Please let me know if this fixes your issue. 

https://github.com/taylorhakes/promise-polyfill/releases/tag/4.0.1

**Comment by mitar** [comment]
I have made a followup pull request: https://github.com/taylorhakes/promise-polyfill/pull/26
