### ISSUE TITLE
package.json main field and file name do not match

### ISSUE THREAD

**Issue by rainydio** [taylorhakes/promise-polyfill#20]
package.json main field is `"main": "Promise.js"`, but actual file name is lowecased `promise.js`. This breaks node and browserify. Changing package.json to `"main": "promise.js"` fixes the problem.

**Comment by taylorhakes** [comment]
OK. I will push out a new version tonight. I apologize for that. Unfortunately my Mac is case insensitive, so I don't see an error on my machine.

If you need a fix now, install version 3.1.0

**Comment by rainydio** [comment]
No problem, thanks

**Comment by taylorhakes** [comment]
This has been fixed in 4.0.2 https://github.com/taylorhakes/promise-polyfill/commit/28cf93d644b2ad98d9fc0317162553d96930e34c. Thanks for reporting the issue.
