### ISSUE TITLE
SCRIPT438: Object doesn't support property or method '_setImmedateFn' 

### ISSUE THREAD

**Issue by polikin** [taylorhakes/promise-polyfill#22]
I get this error in IE10

`SCRIPT438: Object doesn't support property or method '_setImmedateFn' `

code: (Browserify)
```
var Promise = require('promise-polyfill');
var setAsap = require('setasap');
Promise._setImmedateFn(setAsap);
```

**Comment by taylorhakes** [comment]
Are you using Babel? Can you post the code after it goes through Browserify? Don't need the whole file, just the part that wraps this code. It may be transformed incorrectly.

**Comment by taylorhakes** [comment]
Ok, figured it out. There is a typo in the readme. The function name is `_setImmediateFn`, not `_setImmedateFn`. I apologize for this error. I will push out a fix right now

**Comment by polikin** [comment]
Thanks!
