### ISSUE TITLE
console is undefined

### ISSUE THREAD

**Issue by ngentile** [taylorhakes/promise-polyfill#25]
Hi @taylorhakes, I think it would be good if we can evaluate if console is defined before fire the console.warm in order to avoid  'console is undefined' in browser like IE8. Yes is OLD! but in same cases we need to give support.

<pre>
  var onUnhandledRejection = function onUnhandledRejection(err) {
    console.warn('Possible Unhandled Promise Rejection:', err); // eslint-disable-line no-console
  };
</pre>

Thank you!! you made a great work!

**Comment by taylorhakes** [comment]
That is a great idea. Do you want to submit a pull request? Otherwise I can do it later today.

**Comment by taylorhakes** [comment]
I just submitted a fix. https://github.com/taylorhakes/promise-polyfill/commit/1e62013091d338ee4cd16227259b92367b4259bf . If you see any issue, please let me know.
