### ISSUE TITLE
Use process.nextTick where available

### ISSUE THREAD

**Issue by mitar** [taylorhakes/promise-polyfill#28]
Promise spec defines that promises should schedule micro tasks. In node.js this is achieved by using `process.nextTick`. So I would suggest that `asap` function first tries `process.nextTick`, then `setImmediate` (ideally, you could try `MutationObserver` before that), and then `setTimeout`.

See the following for more information: http://stackoverflow.com/a/25933985/252025

BTW, why `setTimeout` does not have `0` but `1` as value? This means that every time you wait for Promise to resolve you add at least 1 ms to waiting. This makes Promises as implemented by this module very slow if there is no `setImmediate`.

**Comment by taylorhakes** [comment]
There has been some discussion on this in several other libraries and in Node. 
https://github.com/petkaantonov/bluebird/issues/591
https://github.com/getify/native-promise-only/issues/53
https://github.com/nodejs/node-v0.x-archive/issues/7714
https://github.com/nodejs/node/issues/2736

promise-polyfill makes the decision to use setImmediate. The way to change it is documented in the [readme](https://github.com/taylorhakes/promise-polyfill#performance). You are free to use nextTick or any other.

The setTimeout 1 is a bug, I will make the change in the next release. Thanks for pointing it out.

**Comment by mitar** [comment]
Hm, maybe it would be good at least to document this? That one might want to replace it on node.js with `nextTick`. Maybe in that section in readme?

**Comment by taylorhakes** [comment]
Which part do you want me to document? I am a little confused. That it doesn't use process.nextTick?

**Comment by mitar** [comment]
Some suggestions what one could use for `_setImmediateFn`. It is just a suggestion.

**Comment by taylorhakes** [comment]
It didn't mean to sound opposed, sorry. I really appreciate suggestions. 

I am worried that adding suggestions for `_setImmediateFn` will just add confusion for beginners/intermediate developers. My opinion is to use `setasap` or another setimmediate polyfill. People are free to use anything else, but I want to leave it up to advanced users.

**Comment by mitar** [comment]
OK.
