### ISSUE TITLE
Polyfill Context

### ISSUE THREAD

**Issue by Diniden** [taylorhakes/promise-polyfill#37]
It would be splendid if there were some other way to set the context the polyfill applies itself to.

(function(root) {
 ...
})(this);

does not give much flexibility for certain build systems. 

For instance, I'd love to have this ability in my start up logic:

import polyfill from 'promise-polyfill';
polyfill(window);

So that the polyfill is applied to the window context should I decide to run the polyfill into a bundling system. Otherwise, in bundling, 'this' becaomes all sorts of weird contexts.

**Comment by taylorhakes** [comment]
You are able to do this if you are using `import` or `require`.

```js
import Promise from 'promise-polyfill';

window.Promise = Promise;
```

Does that work?

**Comment by Diniden** [comment]
This does not work if the polyfill is externally bundled as its own bundle. 

So the scenario for this build system: it takes in third party libraries and bundles them into standalone bundles. 

Then modules requiring the third party libraries get them loaded in via AMD. 

It's difficult to single out libraries for non bundling as that generates too many special cases in the procedure.

**Comment by taylorhakes** [comment]
@Diniden I am confused how you want the library to work. You said you wanted to do this
```js
import polyfill from 'promise-polyfill';
polyfill(window);
```

I gave you that ability
```js
import Promise from 'promise-polyfill';
window.Promise = Promise;
```

You can even create the polyfill function
```js
import Promise from 'promise-polyfill';
function polyfill(globalObj) {
  globalObj.Promise = Promise;
}
polyfill(window)
```

I feel like you want the library to do something that is not possible with Javascript. There is no way to magically return a module without attaching to `this`, using `module.exports` or using `define`. Do you just want `define`? You mentioned you are using AMD.

If you could tell me how to change this library's code to make it work for you, that would be really helpful.

**Comment by Diniden** [comment]
It seems I am a bit of a dummy. Yes:

```
import Promise from 'promise-polyfill';
window.Promise = Promise;
```

Works for me :)

Me being a dummy though, I gave my question a lot of un-needed thought and came up with a solution I thought I needed:

```
var promisePolyfill = (function polyfill(root) {
  // The code....
  return polyfill;
})(this);

// I could now:
promisePolyfill(myOwnContext);
```

But that being said....I don't really need that...You may close this and hide my shame now :) thanks for your time regarding this!
