### ISSUE TITLE
Recommended deployment approach - override browser support or not?

### ISSUE THREAD

**Issue by rarkins** [taylorhakes/promise-polyfill#40]
I see that the default behaviour of this polyfill is to override/replace the "native" browser Promise support. At least, that's how I understood the [Changelog message for 2.0](https://github.com/taylorhakes/promise-polyfill/blob/0f43cadfe480a6affe3a3100424ab4e524c03518/CHANGELOG.md#200):

> This means the library will not use built-in Promise by default. This allows for more consistency.

So clearly "consistency" is an advantage of that - are there known disadvantages? e.g. would it be slower than native Promise on some or all browsers?

I was going to instantiate like this:

```javascript
if (!window.Promise) {
  window.Promise = require('promise-polyfill');

  window.Promise._unhandledRejectionFn = function(err) {
    ExceptionHandler.error(err);
  };
}
```

but thought I'd check here first.

Note: catching uncaught rejections and making sense of them is an important requirement for me.

**Comment by taylorhakes** [comment]
@rarkins Before version 2.0, this library would return native Promise if it existed from `require`. The change made it so you could expect `promise-polyfill` to always be returned from `require` and not have to guess whether you got a native Promise or this library. There are no downsides to this change.

As for the code you showed, I think that is looks good. By default `promise-polyfill` will log unhandled rejections to the console. I am not sure what your function `ExceptionHandler.error` does, but it is fine to override the default behavior however you like.

**Comment by rarkins** [comment]
Hi @taylorhakes, thanks for the response and confirmation.  By the way, this wasn't too easy to figure out - I think I only found it by searching the repo for `window.Promise` and finding the changelog. Anyway, I have no problem with your approach and will update my code.
