### ISSUE TITLE
is there a way to use this with plain angular project?

### ISSUE THREAD

**Issue by arsinawaz** [taylorhakes/promise-polyfill#42]
Hi, i want to use it in plain angular project which does not have bower or npm setup. Is it possible to include and use this poly-fill? i am new in the environment.

Any help is appreciated. Thanks

**Comment by crookedneighbor** [comment]
@arsinawaz There are direct downloads of the js files that you can vendor into your project https://github.com/taylorhakes/promise-polyfill#downloads

**Comment by taylorhakes** [comment]
Thanks @crookedneighbor . I am going to close this as the correct answer.
