### ISSUE TITLE
How about publishing to CDNjs / jsDelivr

### ISSUE THREAD

**Issue by englishextra** [taylorhakes/promise-polyfill#43]
They dont have this polyfill yet, and it appers that it really works nice and doesnt provide custom property name to global object, so you neednt rewrite your code, just leave it native.

**Comment by taylorhakes** [comment]
Thanks for the suggestion. I will look into this.

**Comment by Aaronius** [comment]
You could use unpkg: https://unpkg.com/promise-polyfill@6.0.2/promise.min.js

**Comment by englishextra** [comment]
@Aaronius I cant prove it right now but once I noticed instability of unpkg.com, perhaps its because its rather new. So cdnjs or jsdelivr is preferale in my case

**Comment by taylorhakes** [comment]
If someone wants to create a pull request for this, I will review it. I don't have time to work on this right now.
