### ISSUE TITLE
use with import

### ISSUE THREAD

**Issue by egauci** [taylorhakes/promise-polyfill#44]
This:
```
import Promise from 'promise-polyfill';
window.Promise = Promise;
import 'whatwg-fetch';
```

Fails because imports are hoisted, and window.Promise will be undefined when whatwg-fetch gets imported.

Would you be interested in fixing this? I can submit a pull request.

**Comment by taylorhakes** [comment]
There isn't a good solution for this in a single file. My suggestion is to create 2 files.

One with: 
`./polyfill.js`
```js
import Promise from 'promise-polyfill';
window.Promise = Promise;
```
Then you can do
```js 
import './polyfill';
import 'whatwg-fetch';
```

**Comment by egauci** [comment]
Thanks. I ended up using a copy of promise-polyfill, modifying it so it worked like the 'whatwg-fetch' polyfill (in other words, with "import './promise-polyfill'".

You probably have a good reason to export the polyfill when it's used as a module, but that doesn't really fit my use case.

Thank you for your work on this. It's a really nice implementation for Promise. I'm using it to support IE 11.

**Comment by taylorhakes** [comment]
It was a tough decision. Originally this library polyfilled by default, but I found users who didn't want the global state changed by default. If I don't polyfill, users always have the option to import and do it themselves. If I do it by default, there isn't a good way to turn it off.

I think the best options is to provide both options. If I get some time, I will create a polyfill file as well.

Thanks for your feedback. I appreciate you using the library.
