### ISSUE TITLE
Auto polyfill

### ISSUE THREAD

**Issue by yangg** [taylorhakes/promise-polyfill#46]
Hi, would like auto polyfill it, just like [github/fetch](https://github.com/github/fetch),
then we can only add an entry to webpack

**Comment by NekR** [comment]
Or just write a bit of a wrapper if you really need that.

**Comment by kjagiello** [comment]
polyfills.js
```javascript
import Promise from 'promise-polyfill';  
window.Promise = window.Promise || Promise;
```

Then add it to the `entry` in your webpack config. Mine looks like following:

```javascript
  entry: {
    main: [
      "./js/polyfills.js",
      "./js/main.js",
    ]
  },
```
