### ISSUE TITLE
Wrong version in bower.json

### ISSUE THREAD

**Issue by lopezdonaque** [taylorhakes/promise-polyfill#49]
Hi,
Could you update version 2.1.0 to 6.0.2 to match with package.json please?

**Comment by bakadev** [comment]
This was causing an issue in my application which runs via an automated builder and when it hit the bower install it would die. So just a tip to anyone else who lands on this issue, if you add the following to your bower.json it will bypass the question on resolving correct version.

`  "resolutions": {
    "promise-polyfill": "6.0.2"
  }
`

**Comment by taylorhakes** [comment]
Please submit a PR and I will update it.

You should probably migrate away from bower soon. https://github.com/bower/bower/issues/2298

**Comment by taylorhakes** [comment]
Updated to 6.1.0
