### ISSUE TITLE
Promise.all arguments is null or undefined

### ISSUE THREAD

**Issue by OhadTs1985** [taylorhakes/promise-polyfill#50]
Hi,

I've noticed that when running the following code on browsers that supports promises and browsers that doesn't support (with this the polyfill) i get a different result:

`Promise.all(null)
.then(function () {
console.log('then');
})
.catch(function (e) {
console.log('catch', e);
});`

**Supported browsers result:**
Calling the 'catch' statement with an error of 'TypeError'.

**Unsupported browsers (with the polyfill):**
Throws an error on the arguments slice, doesn't call the 'catch' statement.

Is this the behavior aimed for in this polyfill?

Thanks,

**Comment by taylorhakes** [comment]
It should behave the same. Would you mind creating a pull request?
