### ISSUE TITLE
Rewrite to es6 modules

### ISSUE THREAD

**Issue by Andarist** [taylorhakes/promise-polyfill#58]
@taylorhakes Would u accept a PR with such rewrite? In current form its treated by bundlers like webpack / rollup as cjs module - thus preventing certain optimizations.

**Comment by taylorhakes** [comment]
I would accept a PR for ES6 modules only. I don't want to include polyfills for other ES6 functionality `Array.prototype.includes` etc.

**Comment by Andarist** [comment]
Cool, I will cook something up.
