### ISSUE TITLE
What is the purpose of _setImmediateFn?

### ISSUE THREAD

**Issue by nlhuykhang** [taylorhakes/promise-polyfill#60]
Hello,
First thank you for your great polyfill
Second I am trying to understand how this polyfill works by reading the code. I do not understand what [_setImmediateFn](https://github.com/taylorhakes/promise-polyfill/blob/master/promise.js#L214-L216) is for. I try executing callbacks without it and thing still works. Could you help me to understand it? Thanks

**Comment by taylorhakes** [comment]
That function is deprecated, but the explanation for `_immediateFn` is in the readme.

https://github.com/taylorhakes/promise-polyfill#performance

**Comment by nlhuykhang** [comment]
Thank you for replying, but what I want to know is why bother using `_immediateFn`. Why do you need to execute functions asynchronously? I tried removing it and the polyfill worked fine

**Comment by taylorhakes** [comment]
Promises are always asynchronous.
```js
var prom = new Promise(function(resolve, reject) { resolve(true); });
prom.then(function(result) {
   console.log('inside promise', Date.now());
});
console.log('after promise', Date.now());
```
In the above code I am not doing anything asynchronous, but `after promise` will log before `inside promise`. If you update the `_setImmediateFn` to be `setasap` or another `setImmediate` polyfill, you will notice a faster time between `after promise` and `inside promise`. Without `setasap` it will be 1-4 milliseconds. If you update it, it will always be < 1 millisecond. You may not need that, but some applications need better performance. It's up to you.

I am not sure what you mean by ` I tried removing it and the polyfill worked fine`. `_immedateFn` is set by default.
