### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by sisou** [taylorhakes/promise-polyfill#64]
I'm getting `Uncaught ReferenceError: module is not defined` at `index.js:227` when loading as
`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>`.

**Comment by taylorhakes** [comment]
Please use the new URL. <script href="https://cdn.jsdelivr.net/npm/promise-polyfill@7/dist/polyfill.min.js"></script>
