### ISSUE TITLE
Doesn't work on IE9 when accessing another domain

### ISSUE THREAD

**Issue by laukstein** [taylorhakes/promise-polyfill#69]
Tested on v7.0.2 and v7.0.0. Works fine on IE10+, not in IE9.

> fetch("http://example.com/api/test")

Always returns `Possible Unhandled Promise Rejection: Error: Access is denied`, no outgoing network requests, nothing new in access.log.

![grabilla em2472](https://user-images.githubusercontent.com/183966/35502550-016fd1fc-04e6-11e8-851a-148f4716ab5b.png)

**Update:** It might be related to https://github.com/github/fetch that I use, since is supported on IE10+.

**Comment by taylorhakes** [comment]
@laukstein I believe this is related to the fetch instance. Promise polyfill shouldn't have any issues based on domain. I am going to close this for now. Please reopen if you are able to reproduce a bug specifically in this library without `fetch`.
