### ISSUE TITLE
Unable to locate global object

### ISSUE THREAD

**Issue by brendanarnold** [taylorhakes/promise-polyfill#73]
I have included the polyfill in a universal app which is served from node and in the browser. I used the following for import into a React component ...

    import 'promise-polyfill/src/polyfill';

and after webpack compile using babel I get the following error

    throw new Error('unable to locate global object');

Any ideas what could be the problem?

Cheers,
Brendan

**Comment by taylorhakes** [comment]
Here is the code that is failing.

```js
 if (typeof self !== 'undefined') {
    return self;
  }
  if (typeof window !== 'undefined') {
    return window;
  }
  if (typeof global !== 'undefined') {
    return global;
  }
  throw new Error('unable to locate global object');
```

What environment is it failing in? Node JS has a `global` object and the browser has `window`. Is it being using in a webworker or something?

**Comment by taylorhakes** [comment]
I am going to close this issue until I get more info. Please feel free to add more details.
