### ISSUE TITLE
Question: Promise is undefined

### ISSUE THREAD

**Issue by Legends** [taylorhakes/promise-polyfill#74]
Webpack + Typescript

1. tsc
2. webpack
3. page loads with bundle.js

I am importing the polyfill like this at the top of my file in IE11
`import Promise from 'promise-polyfill'; `

When the page is fully loaded, I check if Promise exists:

![image](https://user-images.githubusercontent.com/966368/36162341-75f62fd8-10e6-11e8-855b-7a293a1ed3b1.png)

![image](https://user-images.githubusercontent.com/966368/36163523-ed32dcec-10e9-11e8-8242-c7459623ef45.png)

**Comment by taylorhakes** [comment]
This library does not automatically attach to the window. If you would like that behavior use this code.

```js
import 'promise-polyfill/src/polyfill';
```
