### ISSUE TITLE
Unexpected token: name (Promise)

### ISSUE THREAD

**Issue by sambshapiro** [taylorhakes/promise-polyfill#76]
I'm having an issue with gulp.

Using this as a dependency for https://github.com/github/fetch. I already updated their package.json to include v7.0.1 of this project and that made no difference.

```
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^
Error: index.js from UglifyJs
SyntaxError: Unexpected token: name (Promise) [./~/promise-polyfill/src/polyfill.js:1,0]```

**Comment by taylorhakes** [comment]
Can you try `7.1.0`?

**Comment by taylorhakes** [comment]
Closing because of no response. Please add more details if 7.1.0 doesn't work.
