### ISSUE TITLE
NPM page GitHub link incorrect

### ISSUE THREAD

**Issue by edmorley** [taylorhakes/promise-polyfill#77]
Hi!

The GitHub link on the [package's NPM page](https://www.npmjs.com/package/promise-polyfill) links to:
https://taylorhakes@github.com/taylorhakes/promise-polyfill.git

Rather than:
https://github.com/taylorhakes/promise-polyfill

The `taylorhakes@` causes Firefox to display a security warning.

This value comes from:
https://github.com/taylorhakes/promise-polyfill/blob/2939a7d7a8a324d7bb4eba3253ae07405b1475e9/package.json#L30

**Comment by taylorhakes** [comment]
Fixed in 7.1.1

**Comment by edmorley** [comment]
Many thanks :-)
