### ISSUE TITLE
Polyfill.js vs Promise.js

### ISSUE THREAD

**Issue by pbb72** [taylorhakes/promise-polyfill#79]
The documentation doesn't make it clear what the difference between Promise.js and Polyfill.js is. The CDN example points to Polyfill.js, while the download link points to Promise.js.

Looking at earlier issues and the changelog, I conclude that one of these overwrites the native promise object (if present) and the other only polyfills it, but this is not clear in the documentation.

**Comment by taylorhakes** [comment]
That is a great point. Thanks for bringing it up.

`promise.js` is meant for use with module systems where you don't want to affect the global object. It's actually a bug that it overrides the global Promise by default. `polyfill.js` is meant as a polyfill that will set the global object Promise if it's not already there.

**Comment by taylorhakes** [comment]
Updated docs and remove promise.js in version 8
