### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by sabapk** [taylorhakes/promise-polyfill#8]
I want to use it for browser. This is my worker code.

var promise;
 if(typeof Promise === undefined) {
      self.importScripts('Promise.js').Promise;
 }

promise = new Promise(function (resolve, reject) {
    var url = ajaxArgs.url || '',
          data = ajaxArgs.data || {},
          type = ajaxArgs.method || 'GET',
          isGet = type === 'GET',
          request = new XMLHttpRequest();
        ..........

**Comment by taylorhakes** [comment]
Are you using in a browser without a window object? If you look at the code, it

**Comment by taylorhakes** [comment]
I have fixed the issue in this commit. https://github.com/taylorhakes/promise-polyfill/commit/049ec5cb21e6a43b66cff27c331570e5f07c9cea  Let me know if you are still seeing the issue.

**Comment by sabapk** [comment]
I am using web workers, which do not have access to window object. So I am not able to use the Promise. To solve this issue, I used your polyfill promise by importing the script.

**Comment by sabapk** [comment]
Can you help me on how I use this Promise in my web workers because now I am getting Promise as undefined.

**Comment by taylorhakes** [comment]
The library didn't originally support Webworkers. I just added support with a new release. The previous logic was a little complicated.

```
module = { exports {} };
importScripts('Promise.js');
var Promise = module.exports;

promise = new Promise(function (resolve, reject) {
  var url = ajaxArgs.url || '',
  data = ajaxArgs.data || {},
  type = ajaxArgs.method || 'GET',
  isGet = type === 'GET',
  request = new XMLHttpRequest();
...

```

You should be able to use it how you wanted to originally now. Download version 2.0.2
```
importScripts('Promise.js');
promise = new Promise(function (resolve, reject) {
  var url = ajaxArgs.url || '',
  data = ajaxArgs.data || {},
  type = ajaxArgs.method || 'GET',
  isGet = type === 'GET',
  request = new XMLHttpRequest();
...
```
