### ISSUE TITLE
Question for converting Firefox addon to Chomium extension

### ISSUE THREAD

**Issue by mikhoul** [taylorhakes/promise-polyfill#80]
I'm migrating to Chromium from Firefox but I have some addons that use promise that I'd like to convert.

Those addons like this one use promise and so they return errors like this: https://i.imgur.com/H8UYYFY.png

What would be the most easy way (since I'm not really fluent with JS) to convert them, would it be by loading the  _polyfill.js_ script from the _manifest.json_ and adding something like that in the beginning of the .js files of the addon ?? 

`var browser = new polyfill(); `

Regards :octocat:

**Comment by taylorhakes** [comment]
Unfortunately `browser` is not a Promise javascript object. It is a Javascript object specific to Firefox, so this library can't be of any help.

Here are the docs on the firefox version
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage
and for Chrome
https://developer.chrome.com/apps/storage

You need to translate to the Chrome version.
