### ISSUE TITLE
Patch Promise.prototype.finally if non-existent?

### ISSUE THREAD

**Issue by ryanelian** [taylorhakes/promise-polyfill#81]
[![image](https://user-images.githubusercontent.com/8892187/38449349-13c6a6f0-3a38-11e8-8758-7018d00ea2dd.png)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)

Being a newer ES2018 feature, the `Promise.prototype.finally` is not available in many platforms (IE, Edge, Node, older version of Chrome and Firefox) yet according to MDN compatibility table...

However, https://github.com/taylorhakes/promise-polyfill/blob/master/src/polyfill.js#L19-L21 only polyfill Promise if not detected.

Should we add more logic to the polyfill?

### finally.js

```js
// Yank the function out of index.js
// I'm assuming this method is compatible with standard Promise stuffs...?

export default function (callback) {
    var constructor = this.constructor;
    return this.then(
        function (value) {
            return constructor.resolve(callback()).then(function () {
                return value;
            });
        },
        function (reason) {
            return constructor.resolve(callback()).then(function () {
                return constructor.reject(reason);
            });
        }
    );
}
```

### index.js

```js
import promiseFinally from './finally';
Promise.prototype['finally'] = promiseFinally;
```

### polyfill.js

```js
import promiseFinally from './finally';

if (!globalNS.Promise) {
  globalNS.Promise = Promise;
} else if (!globalNS.Promise.prototype['finally']) {
  globalNS.Promise.prototype['finally'] = promiseFinally;
}
```

> Just patch the missing method, not the whole `Promise` if possible...

**Comment by taylorhakes** [comment]
I like the idea, but I would like to hear other people's opinions. Are there any major drawbacks to adding finally to native Promise? Will it be confusing in any way?

This library hasn't altered native promises in the past, but it may make sense in this case.

If this goes forward it will be a part of the next major release 8.0, since I consider this a breaking change for the polyfill.

**Comment by watert** [comment]
Maybe another way is to replace the whole Promise object when the finally method is missing.

**Comment by taylorhakes** [comment]
@watert  I would prefer not to do that because there are some performance benefits to using native Promises, but it does make the API consistent.

@ryanelian I think it makes sense to move forward with your proposal. Do you have time to create a PR with your proposed change?

**Comment by taylor-cedar** [comment]
I will take a look at implementing it this week

**Comment by taylorhakes** [comment]
Just merged to master for version 8. Will update with new version of NPM soon. https://github.com/taylorhakes/promise-polyfill/commit/f13a09f5c2ef8ac45255f9f54b97f7cd302c2a08
