### ISSUE TITLE
_unhandledRejectionFn not available on native Promise

### ISSUE THREAD

**Issue by darkylmnx** [taylorhakes/promise-polyfill#83]
I've been noticing a weird bug, **_unhandledRejectionFn** doesn't seem to fire.

My guess is : native Promise doesn't do anything with **_unhandledRejectionFn**, and because you do not override it when it exists and only pathc **finally**, this func does not fire.

A solution would be to patch/polyfill the whole Promise if the native Promise cannot handle _unhandledRejectionFn.

Or do you see another solution ?

**Comment by taylorhakes** [comment]
`_unhandledRejectionFn` is specific to `promise-polyfill` and not available on standard Promises as you mentioned. There is no way to add it to standard Promises. If you want use it always, you can just replace the global Promise with `promise-polyfill`. That will allow you to use it whether or not Promises exist in the environment.

```js
import Promise from 'promise-polyfill';

window.Promise = Promise;
```

**Comment by darkylmnx** [comment]
that's what I did for the moment but as you patched the `.finally()` method on the native Promise, I thought there was a way to do so with `_unhandledRejectionFn `

I think you should mention this on the docs, mention that `_unhandledRejectionFn `only works if you replace the native Promise I mean

**Comment by taylorhakes** [comment]
I updated the readme with a warning
