### ISSUE TITLE
Module not found: Error: Can't resolve './finally'

### ISSUE THREAD

**Issue by smohadjer** [taylorhakes/promise-polyfill#86]
I have installed this polyfill (v8.0.0) using yarn and am importing it in my typescript file like this:

```
import {deepSet} from './deepSet';
import {deepGet} from './deepGet';
import 'whatwg-fetch';
import Promise from 'promise-polyfill';
import merge from 'deepmerge';
```

But when I run npm run webpack I get following error:
```
ERROR in ./node_modules/promise-polyfill/src/index.js
Module not found: Error: Can't resolve './finally' in '/Users/sm/Documents/vi/biotope-configuration/node_modules/promise-polyfill/src'
 @ ./node_modules/promise-polyfill/src/index.js 1:0-39 148:31-45
 @ ./configurationLoader.ts
```

The module finally.js exists here:
`node_modules/promise-polyfill/src/finally.js`

Any idea what is wrong?

**Comment by taylorhakes** [comment]
I am not sure what is wrong. I haven't seen that error before. Can you try importing in node js and see if it works?

**Comment by taylorhakes** [comment]
Closing until new details are provided

**Comment by jh4rri** [comment]
Hi

I have also received this error in the V8.1.0 release.  The only work around we have found is making this change directly your index.js file, which obviously we don't really want to have to do:

Changed the first line to this (added .js extension to "./finally"):
import promiseFinally from './finally.js';

After this change, I don't get the error and Promise is then supported in IE11.

![promise-polyfill error](https://user-images.githubusercontent.com/42969020/52328977-5c0d3900-29e9-11e9-9558-7a820977d35d.png)

**Comment by RiZKiT** [comment]
Could this be related https://github.com/Microsoft/TypeScript/issues/16577?

**Comment by taylorhakes** [comment]
@jh4rri It looks like you are not bundling files together for the browser. This library does not support running directly in the browser without bundling.
