### ISSUE TITLE
package.json is on version 8.0.0 but bower.json is 7.1.0

### ISSUE THREAD

**Issue by olane** [taylorhakes/promise-polyfill#89]
We're still using bower but can't download the latest version of this library from it, I think because the bower file is out of date.

Downloading "7.1.0" from bower actually seems to download version 7.1.2. Bower is also offering us "7.1.2" which does download the version it says it's downloading. Version 8.0.0 is not available.

We're planning to switch over to npm but in the meantime have resorted to targeting the git repository URL with a commit hash which isn't ideal.

**Comment by taylorhakes** [comment]
Please feel free to submit a PR to update bower

**Comment by mischah** [comment]
npm version is `8.0.0` but the latest tag is `7.1.2` 🤔

Compare: https://www.npmjs.com/package/promise-polyfill with https://github.com/taylorhakes/promise-polyfill/releases
