### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by vinnymac** [taylorhakes/promise-polyfill#9]
It is unclear to me what browsers this polyfill supports. [Caniuse shows IE9/10/11 and Safari 7](http://caniuse.com/#feat=promises) not supporting native promises. Does this poyfill support those browsers?

The minimum supported browser should be documented in the readme.

Thanks

**Comment by taylorhakes** [comment]
I added a minimum browser support to the Readme https://github.com/taylorhakes/promise-polyfill/commit/21e1deb7c23990b862e2a1f546deb04a4ece856b . It should work in every major browser and all versions. If you see any issues please let me know.
