### ISSUE TITLE
Polyfill with build: error?

### ISSUE THREAD

**Issue by limonte** [taylorhakes/promise-polyfill#95]
I wonder how reliable is polyfill with this badge:

![image](https://user-images.githubusercontent.com/6059356/45033657-d4985400-b05d-11e8-934f-be9008bfcbdb.png)

Also, consider enabling the daily build in TravisCI: https://docs.travis-ci.com/user/cron-jobs/

If a software isn't tested on a daily basis, it's broken.

**Comment by inf3rno** [comment]
It passes the tests in Travis. I am not sure why it writes build error.

**Comment by inf3rno** [comment]
I checked again. The 8.1.0 and the master branches have an error. According to the logs they timeout by npm install. I think it is ok-ish to have a Travis error. If the dev machine does not have travis there is no way to test it. Hopefully this will be fixed in a later release.

**Comment by inf3rno** [comment]
https://github.com/taylorhakes/promise-polyfill/commits/master?before=1cea042bfcefc04d8d379d0463d7def278ed907a+35
This appear to be common and if you check they don't appear to be Travis related errors. Some of the commits fix syntax error. Using a proper branching model would help to keep the master working. This is embarrassing I think. I'll check, maybe there is an alternative.

**Comment by inf3rno** [comment]
There is another Promise polyfill: https://github.com/stefanpenner/es6-promise it was extracted from RSVP. I think we should use that instead.

**Comment by limonte** [comment]
> There is another Promise polyfill: https://github.com/stefanpenner/es6-promise it was extracted from RSVP. I think we should use that instead.

Yup, and much more popular. Thanks for the valuable feedback, @inf3rno! stefanpenner/es6-promise seems to be the right choise.

**Comment by taylorhakes** [comment]
@inf3rno @limonte The build error is an issue with the Travis badge. If you click on the link you can see that the build passed. I will rerun travis tonight and hope that it is resolved.

Master has never been in a state of a failed build and no I didn't merge changes with syntax errors. Your link is all commits on master, which contains commits from other people's branches when they merged. I don't force people to squash before merging.

You are free to use whatever library you want and if you like another library better, great. But please do not degrade a project before understanding the details. You comments here carry weight to others and is disrespectful to the people who worked on this project.

**Comment by inf3rno** [comment]
![failing build](https://user-images.githubusercontent.com/408911/45182495-ad8a7f80-b221-11e8-8af2-ccc5286b3b5f.png)

...

**Comment by taylorhakes** [comment]
@inf3rno I am not disputing your facts. I am saying you are not being polite. Myself, nor anyone else on this project gets paid. I try fix issues as they are raised. This issue was brought up 2 days ago and was completely an issue with Travis. No tests were failing. As I said, I am happy to fix the issue by rerunning Travis and am thankful that someone brought the issue to my attention.
