### ISSUE TITLE
IE11/EDGE - function connect fails

### ISSUE THREAD

**Issue by steelraiden** [taylorhakes/promise-polyfill#99]
in 
ResizeObserverController.prototype.connect_ = function ()

// Subscription to the "Transitionend" event is used as a workaround for
// delayed transitions. This way it's possible to capture at least the
// final state of an element.
**document.addEventListener('transitionend', this.onTransitionEnd_);**

document.ontransitionend is undefined in IE11/EDGE

**Comment by taylorhakes** [comment]
I don't think this has to do with this library. Please reopen if you have more details
